const ReportFooter = () => {
  return (
    <div className="mt-8 print:mt-6">
      {/* Separator Line */}
      <div className="h-1 bg-gradient-to-r from-red-700 via-red-600 to-red-700"></div>

      {/* Professional Footer Section */}
      <div className="bg-red-700 text-white p-6 sm:p-8 print:bg-red-700">
        {/* Terms and Conditions */}
        <div className="mb-6">
          <p className="text-sm font-bold uppercase tracking-wider mb-3">Important Notes</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs sm:text-sm leading-relaxed opacity-95">
            <div>
              <p>✓ All information is confidential</p>
              <p>✓ Report is valid as per company records</p>
            </div>
            <div>
              <p>✓ For inquiries contact management</p>
              <p>✓ Generated by SmartERP System</p>
            </div>
          </div>
        </div>

        {/* Bottom Footer */}
        <div className="border-t border-red-600 pt-4 text-center text-xs sm:text-sm">
          <p className="font-semibold mb-1">
            © {new Date().getFullYear()} All Rights Reserved
          </p>
          <p className="opacity-90">
            SmartERP • Professional Business Management System
          </p>
          <p className="text-xs opacity-85 mt-2">
            Generated: {new Date().toLocaleString("en-PK")}
          </p>
        </div>
      </div>

      {/* Print Footer Line */}
      <div className="hidden print:block h-1 bg-red-700"></div>
    </div>
  );
};

export default ReportFooter;
