ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS purity_karat INTEGER;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS gross_weight NUMERIC(12,4) NOT NULL DEFAULT 0;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS net_weight NUMERIC(12,4) NOT NULL DEFAULT 0;
